### ISSUE TITLE
Encapsulation: Replace the use of window.tangramPlay , window.editor, etc.

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#121]

**Comment by louh** [comment]
What do you want to replace it with?

My suggestion is to export tangramPlay as a singleton object.

in tangramPlay.js for example

```js
class tangramPlay {
    // code
}

// I think:
export default new tangramPlay({ /* options */})
```

In the other modules that require access to some part of tangramPlay we then import its instance.

```js
import {tangramPlay} from `../TangramPlay.js`;

/* code */
tangramPlay.editor.doSomething(withMyComponentData);
```

What is the benefits of doing this?
- No `window.*` global pollution!
- No need to pass in references to things via arguments (which I never liked, since it created functions that never actually needed those references but needed to pass to other functions... it got messy)
- Keeps it in the same concept as export/importing other modules.

Just curious about your thoughts, let's compare notes.
