### ISSUE TITLE
ColorPicker: error when change from string color

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#140]

**Comment by patriciogonzalezvivo** [comment]
![00](https://cloud.githubusercontent.com/assets/346914/9061026/46bad64a-3a8f-11e5-93c4-90c7d2f2134b.gif)

**Comment by louh** [comment]
@patriciogonzalezvivo @sensescape 

![aug 07 2015 12 37](https://cloud.githubusercontent.com/assets/2553268/9140701/1dace9f4-3d01-11e5-884c-e9f2adf894c2.gif)

I have fixed this on a local branch.

Couple of observations.
- I had to press "enter" after typing in a color to get the widget color to change. In the GIF above the widget color changed after someone was done typing. This might be a regression?
- If I typed gray _inside_ quotes, instead of without them, this would not work. Should it work?

**Comment by patriciogonzalezvivo** [comment]
yeah… : / it’s updating the position and not syncing the color
on the past we didn’t had this because it construct a new pair of key~widgets every time you stop writing

**Comment by louh** [comment]
OK, I'll PR this fix in https://github.com/tangrams/tangram-play/pull/143
and follow up on the updating problem in a separate branch.

**Comment by patriciogonzalezvivo** [comment]
Perfect!

**Comment by louh** [comment]
Still needs work:

A named CSS color inside of quotes, like so:

![screenshot 2015-08-10 10 45 18](https://cloud.githubusercontent.com/assets/2553268/9174297/f1c2b578-3f4c-11e5-804c-e56f78c26d63.png)

breaks the colorpicker widget. Named CSS colors with _no_ quotes works fine, and hex values inside of quotes work fine. Tangram behaves as expected, so the problem may lie in the parser.

**Comment by patriciogonzalezvivo** [comment]
Fixed here:
https://github.com/tangrams/tangram-play/commit/8842cbfbe53e0ec122837494f7776016e0bd2648
