### ISSUE TITLE
Widgets don't get erased when bookmarks are clean

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#198]

**Comment by patriciogonzalezvivo** [comment]
![00](https://cloud.githubusercontent.com/assets/346914/10291933/677aa2ae-6b7a-11e5-862a-df384d74d52a.gif)

**Comment by louh** [comment]
So it appears that the bookmarks aren't getting cleared because `findMarks()`, [here](https://github.com/tangrams/tangram-play/blob/widgets/src/js/addons/WidgetsManager.js#L88), can't actually find any booksmarks at the given range.

Instead, if I add +1 to the lines, it seems to find the bookmarks and behave as desired.

I am going to push a commit that shows this working -- but only up to a certain point.

After some time, the line numbers seem to get even more out of sync. So on longer documents, you would have to say line+2 in order for it to get cleared. I have no idea what's causing this to happen. Thoughts?

**Comment by louh** [comment]
Gonna explore a hunch that somehow blank lines are not being counted when CodeMirror determines line number.

**Comment by patriciogonzalezvivo** [comment]
This is weird... I got this working... on a previus commit

**Comment by patriciogonzalezvivo** [comment]
I revert the "+1" to the lines... the error was actually in TangramPlay.getKeys(from,to) and the fact that .findMarks() dont' work well with ranges of one character... so I fix it by searching for keys and asking for key ranges
https://github.com/tangrams/tangram-play/blob/widgets/src/js/addons/WidgetsManager.js#L81-L105

**Comment by louh** [comment]
:D CLOSED!!!!
