### ISSUE TITLE
Make default API key functionality stricter / or remove

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#259]
We may need to revisit the default API functionality: https://github.com/tangrams/tangram-play/search?utf8=%E2%9C%93&q=default_api_key

I realize it serves a purpose now, making examples accessible, without exposing our key in a way that is easily/accidentally copy-pastable. However, it can also lead to unexpected behavior. Today I had a lengthy period of confusion where I couldn't properly test our dev server because the API was being automatically added, and the requests were failing as a result. Perhaps it just needs to be more explicitly limited to our production environment (vector.mapzen.com).

Related, we can ultimately provide a less opaque UX flow by prompting people to add or sign up for an API key.

**Comment by bcamper** [comment]
cc @louh for thought, not urgent

**Comment by louh** [comment]
Instead of a blanket replacement [of all *.mapzen.com/**/*.(geo|topo)json URLs](https://github.com/tangrams/tangram-play/blob/2b5128d28d567216cab8b7ef201eb46d0911bcad/src/js/TangramPlay.js#L410) in [the entire YAML](https://github.com/tangrams/tangram-play/blob/2b5128d28d567216cab8b7ef201eb46d0911bcad/src/js/TangramPlay.js#L410) would it make sense to look at it like a whitelist: only append API keys to the specific cases where we know it's needed. Basically:

- Only values in the `sources/**/url` keys (or values that is referenced by a YAML variable in that key)
- Only URLs that use the host name `vector.mapzen.com`
- Only URLs with the file extension `topojson`, `geojson` or `mvt`

By looking up only in some keys I'm hoping to get away from regexing the entire file to do API key replacement and then I think we can make rules easier to manage in case those conditions change in the future.

**Comment by bcamper** [comment]
Limiting it to the existing patterns for Mapzen **vector tile** production services only would make sense, so `vector.mapzen.com`, with each of the currently supported formats. That way we don't risk catching non-production services, non-tile services, or non-Mapzen services.

**Comment by louh** [comment]
See commit ec8c5c295715177dc56290c1fc3857a444c02338

I should write a test for this

**Comment by louh** [comment]
As of this merge the API key masking behavior is defined as such: _only_ mask an API key if:

- a URL matches the `vector.mapzen.com` hostname
- the URL matches the `topojson`, `geojson`, or `mvt` tile formats
- the API key, if provided matches a "blacklist" of Mapzen-internal keys

This does not yet check that the url is in the `sources/**/url` keys (or values that is referenced by a YAML variable in that key), but this could be added later.

Tests are provided!
