### ISSUE TITLE
can't drag scroll bar in Chrome

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#313]
![noscrollbar](https://cloud.githubusercontent.com/assets/459970/14643670/4c33525a-061d-11e6-99c0-0c58b0102f79.gif)

seems to work fine in Safari & Firefox ¯\\\_(ツ)\_/¯

**Comment by louh** [comment]
I had wondered if this is because I made the scrollbar so narrow that it's hard to grab onto, but your GIF seems to indicate that it's being ignored completely, which might be a different issue. Can I try a thing: I'd like to expand the width of the scrollbar to something so wide you can't possibly miss it (e.g. 30 pixels or so) -- it's controlled with CSS, so it's something we can adjust in the web inspector, and see if it's still refusing to drag.

**Comment by meetar** [comment]
More details: if I scroll with the scrollbar first, the bar is draggable, and remains draggable after the first drag as long as I don't move the cursor from the scrollbar. But if I do anything else, include type or move the mouse off of the scrollbar, it becomes undraggable again.

**Comment by louh** [comment]
It all comes down this line in CodeMirror here: https://github.com/codemirror/CodeMirror/blob/e2ad4f121aaff921a713d433aec42083917050d1/lib/codemirror.js#L666

It measures the width of the scrollable area and calculates the difference between the node's `.offsetWidth` and `.clientWidth` properties. The difference is the width of the native scroll bar. Given very similar OS and browser version, my native scroll bar width is 15pixels, and but on @meetar's system, this scrollbar width is 0 (that is, `offsetWidth === clientWidth`).

When this scrollbar width is zero, CodeMirror behaves _very differently_. It calls this internal `zeroWidthHack()` method (https://github.com/codemirror/CodeMirror/blob/e2ad4f121aaff921a713d433aec42083917050d1/lib/codemirror.js#L464-L469), causing the scroll bar to _not be usable_ if it's ever less than 18px wide. In other words, the _easiest_ fix for this is to permanently set the scrollbar to 18px wide at minimum.

What's not clear is why `element.offsetWidth - element.clientWidth` is `15` on one system and `0` on another, and whether there's anything we can do make this behavior consistent. It's likely there's a combination of hardware and OS settings (Macs do silly things with scrollbar floating depending on what screen you're using and what pointer devices you have attached) and this might affect browser's `clientWidth` behavior.

For now, I will table the issue until we get more reports and see if this is also affecting other people.

**Comment by louh** [comment]
It's occurred to me that the easiest solution to this on our end is to force an override to the `pointer-events` property in CSS. We can add `pointer-events: auto !important;` to CodeMirror's scrollbars to prevent this from occurring. I don't know if this creates other problems in the editor UI (since CodeMirror seems to believe the scroll bars are not present) but we can give it a try, and see what happens. What do you think, @meetar ?

(Thankfully, this solution should be non-destructive for users where the scroll bar is already working fine!)

**Comment by meetar** [comment]
Seems to work – I added it to the `.CodeMirror-vscrollbar` style in the
element inspector (described there as being derived from
codemirror.css:175).

:+1: :shipit:
