### ISSUE TITLE
don't dismiss "Open a Scene File from URL" on failure

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#314]
When Opening from URL, if the URL is not accessible a warning appears saying "Failed to Fetch", with a button "Continue" – after clicking "Continue" the modal disappears and the process exits back to the editor.

It might be nicer to fail back to the "Open a Scene File from URL" window, so you have the chance to edit the URL without having to start the whole process over.

**Comment by louh** [comment]
After spending a couple aborted efforts on this over the past few months (it sounded like an easy, extremely reasonable request!), I think the best thing to do is to meet you halfway and call it done.

As of commit 8f87bcc71b8e2c751d1b6b85312d1f0e8dfacf8c, the Open from URL modal now remembers the last input you entered (regardless of failure or success). This would allow you to edit the URL if something went wrong, or easily reload that scene if you need to restore it to its previous state.

However, you will still need to access the "Open from URL" modal manually, via the menu bar. Automatically falling back to opening that modal is the pain point here: basically, whenever Tangram Play is asked to load a file, there's a laundry list of things it needs to do to make that happen, any of which can fail for whatever reason. When something does go wrong, it's easiest to just bail at that point and drop the user back out of the process. In order to restore the modal, we would essentially need to pass knowledge of that action all the way through the process, and make it so that any error condition will be able restore to that point.

This isn't necessarily un-doable. But it's a much more complex problem to solve, and my previous two efforts to do it was felt unwieldy and introduced more bugginess. There's probably a "right" answer here, but it doesn't feel like I can answer it when I'm essentially re-engineering the load process for just this one use case. So, rather than go through all that work right now, I think only remembering the last attempted URL input is a fair compromise, and we'll revisit this much later if and when other components start needing to recover its state from an error condition.

**Comment by meetar** [comment]
🆒
