### ISSUE TITLE
bad URLs in import block prevents map formatting changes in Tangram Play

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram-play#391]
steps to recreate:

- add block or map style that doesn't exist to the `import:` section, e.g. `- https://tangrams.github.io/blocks/line/dash.yaml` (or anything that 404s)

- while the code panel will be responsive, the map panel will no longer refresh when you try to disable a layer, or modify the `draw` parameters of a line or polygon

- 5-10 seconds after removing the bad url in the import block, any formatting changes will appear

suggestion: offer pop-up menus with available blocks and map styles

**Comment by louh** [comment]
@bcamper Can / does Tangram report errors when an import fails to load?

The problem to fix here is that if network requests fail, it does so silently after the scene is already sent to Tangram, so there's no feedback when imports stop working. The suggestion to pop-up available imports is a good one and I want to add that eventually (#305) but it doesn't solve the problem which is you can still have a scene with a bad URL (or a scene with a URL that used to be good, but has since become bad).

An alternative to this is for Tangram Play to check network availability of all resources itself, which may not be a bad thing -- it's possible that Play needs to know about all of them anyway.

**Comment by bcamper** [comment]
Yes, we can make Tangram report a warning/error event back to Play when it fails to load an import. I'll open a ticket for that.

**Comment by louh** [comment]
Currently in a progress branch - the error that's generated here when an import fails will appear in a popup window over the map:

![screenshot 2016-10-04 11 29 17](https://cloud.githubusercontent.com/assets/2553268/19164311/6c5d4a8c-8bcd-11e6-8457-e5a63a6ab66d.png)

This should (hopefully) provide enough visual feedback to understand when a scene has errors so changes will prevent it from updating. Will this work for now?

**Comment by louh** [comment]
Calling this closed, because bad URL imports are more obvious now.
