### ISSUE TITLE
Save screenshot filename with z/x/y map location

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-play#474]
So it can be recreated later :)

**Comment by louh** [comment]
Having just spoken to you in person, writing for future reference:

Filenames can use dashes (`-`) as delimiters between x/y/z because forward slashes are not file-system friendly.

There's no way to enforce a filename for a dynamically created canvas export in Safari. We are able to save files to a backend soon, so if we wanted to do a round-trip where we save the screenshot to the server and download the file with the correct name, we can solve this.
