### ISSUE TITLE
Previous location search text should clear on focus

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#496]
Steps:
- Search for a location, click a result.
- Click out of the search box.
- Click back into the search box to re-focus.

Result:
- Text from the previous search is left in the box, and needs to be manually erased to do a new search.

Expected:
- Text from previous search is cleared, so you can immediately start typing a new search.

**Comment by bcamper** [comment]
@louh I believe this is a React regression?

**Comment by louh** [comment]
It changed when we migrated that component to React, but regression is a harsh word for it. We're now using [React-Autosuggest](http://react-autosuggest.js.org/) to handle this, which is based on WAI-ARIA guidelines. In comparison with other existing geocoder / autocomplete search inputs, nobody else actually clears the previous input, so I'm not likely to consider that "expected" behavior again. We were "sort of" getting away with it because we used the input's placeholder property to indicate your current position.

There are two options for clearing your previous input quickly:

- The first is to press Escape _twice_, which is the recommended way of clearing previous search input by WAI-ARIA:

> With focus in a text box, press Escape

> If there is no text in the text box, pressing Escape closes the drop-down if it is displayed.
For an editable autocomplete that has text in the text box that was both typed by the user and auto-completed by highlighting a choice using the keyboard, the auto-completed portion of the text is cleared and the user typed characters remain in the text box. The drop-down list is closed. To completely clear the text box contents the user must use the backspace key to remove the typed characters. This is how the Google search box in the Firefox UI works. Recommend that pressing the Escape key again completely clears the text box rather than relying on only the backspace key.

- We can automatically select the previous text input, rather than clear it immediately. This does allow you to press backspace one time to clear the input. This is how the location bar works in browsers, so it helps strengthen the location bar metaphor for the location search input.

**Comment by bcamper** [comment]
Got it. I would probably lean towards the second option (select text)? But I'm cool to follow the other guideline if you think it's more appropriate (it's less usable *to me*, but if it's an industry recommendation, hopefully there's a reason... :)

**Comment by louh** [comment]
I think the second option can co-exist with the first, so I'll explore that soon.
