### ISSUE TITLE
Outline color does not show a swatch

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram-play#536]
![image](https://cloud.githubusercontent.com/assets/1190866/17875044/45516b56-6884-11e6-80d1-5c03a461e4a7.png)

The colour of lines is shown in a circle, but not that of outlines

**Comment by louh** [comment]
@pnorman Thanks! This is fixed now.

For a little bit of context, we used to add the colorpicker to anything with a `color:` key, but that needed to be much stricter, for two reasons: (a) it's possible to have a definition, like shader code, you want to be called `color:` but do not hold values a colorpicker could provide; (b) some blocks like `font:` use `fill:` instead of `color:` (a holdover from SVG syntax) and we did not want to make it appear that `color:` is a valid property here. So right now we are only whitelisting instances of `color:`, and will likely need to do it on a one-by-one basis.
