### ISSUE TITLE
Getting console error when scene file is added without a #

### ISSUE THREAD

**Issue by irealva** [tangrams/tangram-play#545]
To recreate the problem navigate to: [https://mapzen.com/tangram/play/embed/?scene=https:%2F%2Ftangrams.github.io%2Ftangram-tutorial%2Fsrc%2FAssets%2Ftutorial-files%2Fmin.yaml](https://mapzen.com/tangram/play/embed/?scene=https:%2F%2Ftangrams.github.io%2Ftangram-tutorial%2Fsrc%2FAssets%2Ftutorial-files%2Fmin.yaml). You can use normal play too - not the embedded version - and it will also throw an error.

Shows up in the console as: 
`embedded.js:48 Uncaught (in promise) TypeError: Cannot read property 'then' of null`

Tangram Play loads correctly anyway, but for some reason we're throwing an error, when the url does not contain a hash.

**Comment by louh** [comment]
There seems to be a race condition here but I'm not sure _why_ it would be the case when the hash isn't in the URL. It's somehow affecting the load process, which has a broken Promise chain: it loads a scene in Tangram, and then elsewhere relies on Tangram's `scene.initializing` Promise to exist. When the hash isn't present, the Promise doesn't exist. The solution seems to be making the `scene.initializing` part of the Promise chain for loading so that it is guaranteed to exist at the line where this error is being thrown. Although I still have no idea how the hash plays into this, this slight restructuring is better way of writing this load process anyway.
