### ISSUE TITLE
Dropdown widgets always select the first option

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#563]
If you click in any dropdown widget the first option is always “selected".
Even when it shouldn't which in other things don’t allow you to select the first option

Example1:
- Click in “new"
- then on the default new map go to line 3 and click next to TopoJSON
- Try to change it to geoJSON

Example2:
Or in this GIF makes imposible to choose "points" on the geometry

![00](https://cloud.githubusercontent.com/assets/346914/18287234/4474e43a-7444-11e6-9d8d-09ad9a2fe5e8.gif)

**Comment by louh** [comment]
Sorry, we totally overlooked this in converting "widgets" to React.

This will be fixed soon. The correct value in a dropdown will be selected. If the value doesn't match something in the dropdown, it will be appended to the options list so that it can be selected, which also allows those values to be retrieved again if a user changes it by accident. These "custom" values are not permanent and will be removed if dropdowns re-render.

**Comment by patriciogonzalezvivo** [comment]
👍
