### ISSUE TITLE
Color picker resets hue when either saturation or brightness values reaches zero

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#576]
![00](https://cloud.githubusercontent.com/assets/346914/18792957/a3cf01be-8186-11e6-8e40-8b27e789123e.gif)

Also once it change HUE to red... block the HUE slider

**Comment by louh** [comment]
Thanks for the report!

This is an issue with the underlying [tinycolor2](https://github.com/bgrins/TinyColor) which is what we are using now to do the color processing. When either the saturation or value (brightness) reaches zero, the hue is reset to zero:

```
> tinycolor("hsl(25, 1%, 1%)").toHsv()
Object {h: 25, s: 0.019801980198019684, v: 0.0101, a: 1}
> tinycolor("hsl(25, 0%, 1%)").toHsv()
Object {h: 0, s: 0, v: 0.01, a: 1}
> tinycolor("hsl(25, 1%, 0%)").toHsv()
Object {h: 0, s: 0, v: 0, a: 1}
```

This is a known issue: https://github.com/bgrins/TinyColor/issues/86

We will have to work around this here by caching the hue value rather than rely on tinycolor's parsing when saturation or brightness is zero.

**Comment by louh** [comment]
Fixed https://github.com/tangrams/tangram-play/pull/577

**Comment by louh** [comment]
Note that one limitation of this is that the caching of hue values do not persist outside the lifetime of the colorpicker, so once it's closed, that value is lost again. A color value of [0.5,0.5,0.5,1] will display with a hue value of 0 (red) because the value itself has no information about the hue anymore.
