### ISSUE TITLE
add `noscroll` option for embed

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#600]
To prevent scrolling the map when scrolling past an embed

**Comment by louh** [comment]
Can you show me a page where you are embedding Tangram Play?

**Comment by meetar** [comment]
Sure! https://precog.mapzen.com/mapzen/website/meetar/terrain-embed-test/blog/terrain-generalization

**Comment by louh** [comment]
Internal Server Error?

**Comment by meetar** [comment]
Works for me – try going to https://precog.mapzen.com/mapzen/website first to make sure you're logged in?

**Comment by louh** [comment]
👍 

OK - what I'm going to do for here is that I'm going to make the map not respond to scroll wheel zoom events when iframed. This will be automatic and will not be a configurable option. For the embedded Play version I'll re-insert manual zoom in/out buttons to compensate.

**Comment by meetar** [comment]
Sounds good.

**Comment by louh** [comment]
Ok - check out your blog post now!

**Comment by meetar** [comment]
Looks good! (I wonder if there's any reasonable way to do something similar for the text editor too? eg only scroll the editor if the scroll starts inside the editor?)

**Comment by louh** [comment]
Yeah - I had the same concerns, but didn't want to overthink the feature request too much initially. You've reached the same conclusions I did - it's "less bad" for the editor to scroll because there is a stop point to it as opposed to the map which just eats scroll events indefinitely.

I've wanted to play with intercepting / forwarding / canceling scroll events for a long time, but have never gotten around to doing it. Part of me believes it's more trouble than it's worth for technical reasons I can't explain until I investigate, the other part of me hopes I might be pleasantly surprised that it could actually work.
