### ISSUE TITLE
"Minified React error #119"

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-play#601]
On Mac OS 10.11.6, Firefox 50.0, when I navigate to https://mapzen.com/tangram/play I see this message:

![screen shot 2016-11-28 at 2 26 31 pm](https://cloud.githubusercontent.com/assets/3371850/20682796/7278703a-b577-11e6-9901-6105832ac85c.png)

After this, when I try to load an example scene from the menu, I see this message and the scene fails to load:

![screen shot 2016-11-28 at 2 33 50 pm](https://cloud.githubusercontent.com/assets/3371850/20682869/c5791294-b577-11e6-9f3b-179e520e711e.png)

**Comment by blair1618** [comment]
Following the React error link: https://facebook.github.io/react/docs/error-decoder.html?invariant=119

```
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a 
component that was not created inside a component's `render` method, or you have multiple 
copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

**Comment by louh** [comment]
This is incredibly difficult to debug because _this error does not appear in a development environment._

**Comment by louh** [comment]
Since I hadn't made any commits to Tangram Play in a few weeks, a React-based error was unexpected. The one commit I made yesterday that rebuilt the application introduced this new error message, but it wasn't a React-based change. As an experiment, I rolled back to the previous commit, which resulted in the same error. So I can rule out that this error was caused by anything that Tangram Play was doing with component `ref`s.

The other clue is this: "you have multiple copies of React loaded."

The other clue is that this error did not appear in my local development environment, but only in production. Therefore, something in production environment was causing React to be installed twice. Here is the sequence of events that caused this to happen:

1. The CircleCI `config.yaml` we were using was specifying node v4, which uses npm v2, which installs peer dependencies automatically.
2. The module `react-color@2.3.3` specifies in its dependencies the latest version of module `react-addons-shallow-compare`. As a result, any deploy process would install the latest version of that module.
3.  The module `react-addons-shallow-compare` then specifies, as a peer dependency, the version of react that matches its version number.
4. React, and `react-addons-shallow-compare`, updated to 5.14.1 just before Thanksgiving.
5. As a result, `react-color` ends up including a more recent version of React than Tangram Play has specified.

As part of this fix, all dependencies that did not cause breaking changes were updated. In particular, we are now using node v6 in the deploy process, which will not install peer dependencies automatically. The `react-color` module has also updated and removed its dependency on `react-addons-shallow-compare` presumably because others noted that it was causing problems for them.
