### ISSUE TITLE
read blob scenes

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#617]
Passing a blob in the `scene` parameter of an embed url, like so:
`https://mapzen.com/tangram/play/embed/?scene=blob:https://precog.mapzen.com/3ecbaf72-6975-48b6-ad75-883d7e9bf6a6`

Throws this error:

`VM20220 embedded.js:23 Fetch API cannot load blob:https://precog.mapzen.com/3ecbaf72-6975-48b6-ad75-883d7e9bf6a6. URL scheme must be "http" or "https" for CORS request.`

Would be great if we could send a blob through here!

**Comment by meetar** [comment]
:+1: Looking good! However I ran into a glitch with a malformed scene-file:

`VM31397 embedded.js:23Tangram v0.11.4 [error]: Scene.load() failed to load blob:https://precog.mapzen.com/cddb95ec-48cf-4a7a-99f3-a351f4e4115b: Cannot read property 'import' of null TypeError: Cannot read property 'import' of null(…)`

In this case the contents of the blob is the literal string "null"

**Comment by louh** [comment]
How did `null` happen?

**Comment by louh** [comment]
So yeah, this error comes from Tangram. On the first load, Tangram Play will display this error but it's just passing it through from Tangram. This is just what happens if you happen to give Tangram a scene file whose contents is the string "null": https://dev.mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/7/95/resources/empty.yaml#16.76675/40.76394/-73.98136

So here's three potential solutions:

(1) On the tutorial side, check contents for "null" before sending a scene url to Tangram Play's iframe.
(2) On Tangram Play, explicitly check editor contents for the string "null" before sending the scene to Tangram.
(3) On Tangram's side, handle this error better somehow.

I feel like (1) might be the most simplest way of dealing with this?

cc @bcamper

**Comment by meetar** [comment]
Agreed – but regardless it's clear it's unrelated to the present issue, so I'll fix that, check that everything works, and close this one.

**Comment by meetar** [comment]
Works :)
