### ISSUE TITLE
'refresh' button on an embedded editor refreshes all embeded editors on a page

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#668]
![refresh](https://cloud.githubusercontent.com/assets/459970/22573176/b422d854-e975-11e6-86b1-f72b6421426c.gif)

**Comment by louh** [comment]
How does this even happen? Theoretically speaking each frame is unaware of another. Interaction in one frame should not affect another frame, so something else is facilitating this communication. Are you by any chance running local versions with BrowserSync on?

**Comment by louh** [comment]
If so, add this line to `gulpfile.js`: https://github.com/tangrams/tangram-play/blob/4eac9ccc347f491228b56db31b087cdd3520ffb5/gulpfile.js#L159

and let me know if this is fixed.

This will be merged to master next week anyway, since this mode causes other problems in local environment testing (it does not play well in browser windows of different sizes).

**Comment by meetar** [comment]
> Are you by any chance running local versions with BrowserSync on?

Yep, I sure was.
