### ISSUE TITLE
Insert UI widgets into Code Mirror DOM

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#68]
Put the UI widgets into the Code Mirror DOM, instead of trying to manually float them in the right position.

**Comment by louh** [comment]
@patriciogonzalezvivo We should continue widget discussion here

**Comment by patriciogonzalezvivo** [comment]
I made mayor changes on the YAML-Tangram parser... now we can have multiple keys per line. Yay! But now I'm fighting with the update system. Hopefully I will have a good base when @louh come back from his vacations. TangramPlay, now is almost fully implemented in ES6, with a OOP structure. Is more clear to read and modular. One big change is that everything that is not part of the core is added as an "addon", including the menu.

**Comment by patriciogonzalezvivo** [comment]
Keys can be fetch by address ( https://github.com/tangrams/tangram-play/blob/gh-pages/src/js/TangramPlay.js#L111 ) which is more expensive because use a double loop; 

```
tangramPlay.getKeyForAddress("/cameras/perspective/type")
```

or by a string containing the "[lineNumber]-[occurrence]" ( https://github.com/tangrams/tangram-play/blob/gh-pages/src/js/TangramPlay.js#L100 ) which is cheaper.

```
tangramPlay.getKeyForStr("2-0")
```

Widgets  will record the last type of fetching coordinate because it's faster.
Once you have the key is easy to make changes because keys stores the address, occurrence on the line, key, value and position of the colon ":" -> so it's easy to guess where the key and value starts/ends. 

```
 {
    address: "/cameras/perspective/type", 
    key: "type", 
    value: "flat", 
    pos: {
                line: 2,
                ch: 12
              },
    index: 0
}
```

I also add some handy interface functions to change the value of a key, See: https://github.com/tangrams/tangram-play/blob/gh-pages/src/js/addons/widgets/ColorPicker.js#L28

```
tangramPlay.setValue(tangramPlay.getKeyForStr("2-0"), "perspective")
```

@louh, hope all this help us have better inline widgets.

**Comment by louh** [comment]
Notes for posterity --
Widget stuff I added yesterday included making each widget instance its own object, so that key information can be stored directly as properties of the widget. (As opposed to storing line-index data as a string value that must be parsed and looked up for key information, so it cuts a step.) What remains is some way of being smarter about how widgets are updated. (If CodeMirror reports lines X through Y have been added, changed, or deleted, make sure the widgets are updated accordingly.) Currently there is a brute force method where on any update, widgets are removed from DOM and rebuilt (and it seems that GlslSandbox.js does its own widget rebuild, a second after edits). This creates a ton of overhead, and causes widgets to lose its connection to any other secondary UI interaction -- for instance, if you open the color picker, you can see its background color change in real time with the user's interaction. Wait one second, and the widgets rebuild. As a result, the color picker stops updating the background color because the connection to the original widget DOM is lost.

Now that widgets are instanced objects, we can add additional methods to allow the editor to make granular updates to the widgets -- so values can be updated without rebuilding DOM, for instance. This is probably not going to be solved immediately because I am going to focus on the color picker itself but this will be the next step to making widget interaction really robust.

**Comment by patriciogonzalezvivo** [comment]
I think we can close this one... right?

**Comment by louh** [comment]
YUP!
