### ISSUE TITLE
include scene name in the <title> tag of the map in tangram/view url and Tangram Play

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram-play#682]
(this may require letting the user edit the file name after it is saved)

**Comment by louh** [comment]
@burritojustice Can you describe your reason for asking for this?

**Comment by burritojustice** [comment]
so people can give and get a meaningful name in their browser tab and search history, and distinguish amongst Tangram Play and View instances open in their browsers

**Comment by louh** [comment]
Thanks for the explanation. Here's a little more context about why I asked. For your described use case we can pretty easily pull the title from the scene API and set the page title after it's loaded.

_However,_ there is a secondary category of uses that might be important to consider: previewing a link in Twitter/Facebook, or having something show up in search engine listings. In these cases, we can't have access to the scene title because title resolution is performed client side, not server side, and Tangram Frame is not a server-side application. So if your use cases were more on this line of thinking we would need to roll this up into a future v2 of Tangram Viewer that processed HTML on the server. (Incidentally, this would also help with simplified scene URLs, which is something I know you have been asking about.)

**Comment by louh** [comment]
I'm going to close this and re-file it in the appropriate repo.

**Comment by louh** [comment]
Whoops, re-opening so we have show title in Tangram Play as well.

**Comment by louh** [comment]
We're now displaying titles of scenes in Tangram Play.
