### ISSUE TITLE
Images/resources fail to load on examples

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#72]
With the example picker no longer force-reloading the page (which is how it should be), example styles that have images and remote resources (like Crosshatch, Sandbox) will not load those resources anymore. That's because the content of the file is being injected directly into the editor (https://github.com/tangrams/tangram-play/blob/gh-pages/src/cm-tangram/ui.js#L188), then turned into a local object URL (like other editor content), and then loaded as a scene.

Tangram uses the URL that the scene was loaded from to determine where other resources should be loaded from, since they are treated as relative paths in the scene file. In these cases, the correct URL/path info has been lost, as the content was "laundered" through CodeMirror.

We need a better way to deal with resources for this editor anyway, so logging this here and will think on it more.

**Comment by bcamper** [comment]
@louh @patriciogonzalezvivo

**Comment by patriciogonzalezvivo** [comment]
Temporal fix, add absolute url paths throuhg rawgit:

https://github.com/tangrams/tangram-sandbox/commit/10a87c964f9ead1aaf52460bc42f2d4deafe8534

**Comment by bcamper** [comment]
I've mostly fixed this with code (in Play) that preserves the original source URL. This URL then gets reset each time you load a new file. But I believe there's still a case where it is not reset -- when you start a "New File".

**Comment by bcamper** [comment]
See https://github.com/tangrams/tangram-play/commit/358f222a92676830cd4e8cc01a8f3149c9fab728 for more info

**Comment by bcamper** [comment]
@patriciogonzalezvivo could you help hook this up to the events for opening a file from disk?

**Comment by patriciogonzalezvivo** [comment]
Sure!

**Comment by louh** [comment]
There's been an ongoing bug related to this where resources won't load if Tangram Play is started up, and recovers a scene from a previous session. In this particular case, Tangram is initialized with  `Tangram.leafletLayer({ scene })`, because it's the first run of Tangram. Is there a way to set the `base_path` here, similar to `scene.load(scene_url, base_path)`?

For additional context, the `scene` variable passed to `Tangram.leafletLayer()` might be a "laundered" Blob URL, because it's possible that it has been a user-modified version of the original scene file.

**Comment by louh** [comment]
Resolved via this release: https://github.com/tangrams/tangram/releases/tag/v0.10.5

Fixed via c9e6433b0342e387db29f8cc0d6fa049d05c3771
