### ISSUE TITLE
add and edit scarab info and html title info

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram-play#734]
It would be handy to be able to edit and add data associated with the scarab and the HTML `title` info, especially after a map is published. 

See also https://github.com/mapzen/mapzen.js/issues/383

**Comment by burritojustice** [comment]
context: lots of people were passing around the link to the cistern article outside of the citylab article, would be good to be able to add and that data to let them know more

**Comment by louh** [comment]
We are going to use the description field currently in the Mapzen Scene API as the "know more" section. The button to display this information will live in scarab, as in here: https://github.com/mapzen/scarab/issues/1

Note that for this implementation, we will not be permitting raw HTML in descriptions because this creates security risks. We will explore rendering Markdown (which is safer) in the future.
