### ISSUE TITLE
Color picker ideas

### ISSUE THREAD

**Issue by souperneon** [tangrams/tangram-play#85]
http://widget.colorcodehex.com/color-picker.html

The top search box has a good format with a color tiles and tiny dropdown and the picker is more conventional

**Comment by patriciogonzalezvivo** [comment]
Looks good to me. We should make a wrapper for loading it in and out.

**Comment by patriciogonzalezvivo** [comment]
@louh can you take a look to it??

**Comment by patriciogonzalezvivo** [comment]
Check the color picker that they are using here... select a color. and will apear: http://www.cssmatic.com/box-shadow
Is pretty nice.

**Comment by souperneon** [comment]
@patriciogonzalezvivo beautiful! I love it :)

**Comment by patriciogonzalezvivo** [comment]
I just check... require jquerry : (

**Comment by souperneon** [comment]
damn :(

**Comment by louh** [comment]
That one is my favorite so far.

I glanced through the code. Like many things written for and with jQuery, _you don't actually need jQuery_, but people continue writing with it because it's an abstraction layer that makes sense. This is one such library: the dependence on jQuery is an assumption, but not a necessary one. Somewhere between the world of starting 100% from scratch and just using an external library, there is the option of porting someone else's code and adapting it for our needs. In this case, I think it is a pretty feasible choice. We only have to start at 50% instead of zero.

**Comment by patriciogonzalezvivo** [comment]
Great point @louh. Let's start working on it.

**Comment by louh** [comment]
Another option :)

http://bgrins.github.io/spectrum/

A few differences
- This has much more recent development activity, so it's more feasible to drop in and not have to modify ourselves
- It does depend on jQuery :-/ (but I would also love to reach out and help this person migrate toward not depending on jQuery, since it is in active development)
- Apparently this was adapted to Chrome, Firefox and Safari webtools, which is a huge plus as far as similar end user experience goes
- No HSB color indicators, which is good if it reduces UI clutter, bad if HSB is actually useful for Tangram colors
- Has a transparency slider, which is good if Tangram colors can use transparency, otherwise it doesn't matter

**Comment by patriciogonzalezvivo** [comment]
Other plus:
* have a color paletes!!

With some designs retouch we can make this beautiful.

:+1:  for helping other projects (specially to get rid of jQuery : )

**Comment by louh** [comment]
Another one. Very customizable, no jQuery. http://www.dematte.at/cpn/

**Comment by patriciogonzalezvivo** [comment]
WOW! that's amazing! And we can start using right away with almost no adaptation... right?

**Comment by louh** [comment]
There's always the possibility that there's something I can't predict! Let me play around with it for a bit :)

**Comment by souperneon** [comment]
I like the simplicity of http://www.dematte.at/cpn/ but looking a little into the future, the idea of creating a color palette is awesome. I envision it like old Tilemill having a floating palette somewhere so the user can see all the colors they have  used in a style and to take that even further, give an easy way to change a color in all places it's used at once.
My vote is for http://bgrins.github.io/spectrum/ :) if we can make that work without drama!

**Comment by patriciogonzalezvivo** [comment]
the floating palette can be add as a separate thing, specially because we will want to style it very carefully over the map or somewhere else.

![concept](https://cloud.githubusercontent.com/assets/346914/8729115/30d3d75a-2bb7-11e5-9bdf-60acd6d28e12.jpg)

**Comment by souperneon** [comment]
me likey ;)
