### ISSUE TITLE
Color picker error on Firefox

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-play#93]
Firefox 39.0

When clicking color picker, nothing appears and an error is logged:
```
TypeError: m is null
```
at thistle.js:66:4

**Comment by louh** [comment]
hey @blair1618 can you see if you can duplicate this and what steps you took? I definitely remember seeing it before, but can't get it to reliably happen - it's possible it got fixed in the interim.

In any case we are swapping out the color picker soon so hopefully it becomes moot anyway

**Comment by blair1618** [comment]
Yup, I can still duplicate it by just going to http://tangrams.github.io/tangram-play/ and clicking either of the color pickers in the default 'blank' style. Probably makes sense just to wait till you have a new color picker.

**Comment by louh** [comment]
Are you on Firefox? Looks like it breaks in Firefox, but works in Chrome.

This could be a problem if something on the Tangram Play side sends unexpected data in Firefox, *or* it's a buggy library. Yeah, since I'm replacing it anyway, I'm going to mark this "wontfix" and hope that a new color picker is going to have a better time.
